### PR TITLE
Add write from process.stdin

### PR DESCRIPTION
**Pull request by whitecolor**
Definitly needed.

### CODE REVIEW

**Comment by whitecolor** [comment]
Any comment?

**Comment by sun-zheng-an** [comment]
Please make it pass the test first.

**Comment by whitecolor** [comment]
Is test not passig because of comit's chages? Could you look in to it, I don't get what Travis CI errors on.

**Comment by sun-zheng-an** [comment]
The error is timeout, because the `process.stdin` is still open after the child process finished.

I implemented this feature before, but drop it by 39b66b19bed5a74428626aeebbfb3faa880be3fa , because I found that it's very hard to make it work on both Node 0.10 and Node 0.12 without some dirty hacking and I don't think we should use `gulp` to do any interactive task.

**Comment by whitecolor** [comment]
> I don't think we should use gulp to do any interactive task.

Why not? `grunt-shell` for example can do it.

**Comment by sun-zheng-an** [comment]
Thanks for giving me this example, you convinced me to add it back.

**Comment by whitecolor** [comment]
Great, hope to see it soon on npm =)

If there are problems with stdin maybe it is worth to add an assertive option to turn it on.

**Comment by sun-zheng-an** [comment]
I already published it to NPM as 0.4.1.

**Comment by whitecolor** [comment]
So I can close this I believe then, thanks.

**Pull request closed without merging**
