### PR TITLE
Add ability to have custom error messages on failure

### PR DESCRIPTION
**Pull request by MikeMcElroy**
Sometimes you'll want to have custom error messages (such as for use with `gulp-notify`).  This adds that feature.

### CODE REVIEW

**Comment by MikeMcElroy** [comment]
Looks like the test failure is because the error message returning under Travis is different from the error returning under my Macbook.  I think I should probably just remove that test because it's kinda weird anyways.

**Comment by sun-zheng-an** [comment]
Could you update the [README](https://github.com/sun-zheng-an/gulp-shell/blob/master/README.md) file for me?

**Comment by MikeMcElroy** [comment]
Sorry, didn't see this -- absolutely.

**Comment by hbrls** [comment]
@MikeMcElroy I'd love another options sth. like `ErrorMesssageFalse_IgnoreErrorsFalse`.

Most of the  `shell commands` will have their own loggings, and they are enough by default. I want them to print the error, and gulp-shell not to re-print it.

`IgnoreErrors: true` will not break the gulp stream.

`ErrorMessage: ""` in your PR will still re-print the error.

Can I assume that this feature will be part of your PR, or is it an irrelevant feature?

**Comment by MikeMcElroy** [comment]
@hbrls I'm not entirely sure I follow -- you're talking about an option to eliminate gulp-shell's consoling out the stderr on error that's different from `ignoreErrors`?  That sounds like it should be a different flag, like `silent: true` or something like that.  I wouldn't mind making a new PR for that, but it doesn't seem germane to this PR.  Let me know if I misunderstood.

**Comment by hbrls** [comment]
You got it.

`quiet: true`, shell is quiet, gulp-shell is logging. (Already there.)

`silent: true`, shell is logging, gulp-shell is quite. (What I want.)

@sun-zheng-an, What's your opinion?

**Comment by MikeMcElroy** [comment]
Just as a note -- I'm planning on using this PR at work to clean up our build process and would love it to be rolled in ASAP.  I have no problem working on an issue like @hbrls is suggesting, but the sooner the better on this ticket for me.

**Comment by hbrls** [comment]
@MikeMcElroy sorry for getting in the way. I will push an pr later.

**Comment by MikeMcElroy** [comment]
No worries, @hbrls, just wanted to keep this one short and sweet.  :-)
selfie-0

**Comment by hbrls** [comment]
@MikeMcElroy I'd to reuse your code. Would you please switch the line order of 

    if (options.errorMessage) {
        var errorContext = _.extend({file: file, error: error}, options.templateData)
        error.message = gutil.template(options.errorMessage, errorContext)
    }
    error.stdout = stdout
    error.stderr = stderr
to:

    error.stdout = stdout
    error.stderr = stderr
    if (options.errorMessage) {
        var errorContext = _.extend({file: file, error: error}, options.templateData)
        error.message = gutil.template(options.errorMessage, errorContext)
    }

so that I can use `err.stdout` and `err.stderr` in the `errorMessage` template

**Comment by MikeMcElroy** [comment]
Done, @hbrls .

**Comment by hbrls** [comment]
@MikeMcElroy :+1: waiting for the merge and release

**Comment by MikeMcElroy** [comment]
bump @sun-zheng-an (sorry to seem impatient) :bowtie:

**Comment by sun-zheng-an** [comment]
@MikeMcElroy 
It looks pretty good.
Thank you!

**Pull request merged**
